forms_app/urls.py
from django.urls import path
from forms_app.views import contatti, lista_contatti, elimina_contatto ,modifica_contatto

app_name="forms_app"
urlpatterns = [
    path('contattaci/', contatti, name='contatti'),
    path('lista_contatti/', lista_contatti, name='lista_contatti'),
    path('elimina_contatto/<int:pk>/', elimina_contatto, name='elimina_contatto'),
    path('modifica_contatto/<int:pk>/', modifica_contatto, name='modifica_contatto'),
]

news/urls.py
from django.urls import path
from news.views import index_root, home, articoloDetailView, listaArticoli, queryBase, giornalistaDetailView,index

app_name="news"
urlpatterns=[
    path('index_root',index_root, name="index_root"),
    path('homeview',home,name="homeview"),
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("lista_articoli", listaArticoli, name="lista_articoli"),
    path("lista_articoli/<int:pk>", listaArticoli, name="lista_articoli"),
    path("queryBase", queryBase, name="queryBase"),
    path("giornalisti/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
    path('index',index, name="index"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base,name='base'),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('news/',include("news.urls",namespace="news")),
    path('voti_app/',include("voti_app.urls",namespace="voti_app")),
    path('gestione_eventi_scolastici/',include("gestione_eventi_scolastici.urls",namespace="gestione_eventi_scolastici")),
    path('corsi_formazione/',include("corsi_formazione.urls",namespace="corsi_formazione")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),


]

forms_app/models.py
from django.db import models

class Contatto(models.Model):
    nome=models.CharField(max_length=100)
    cognome=models.CharField(max_length=100)
    email=models.EmailField(max_length=200)
    contenuto=models.TextField()
    

forms_app/forms.py
from django import forms
from .models import Contatto

class FormContatto(forms.ModelForm):
    class Meta:
        model=Contatto
        fields="__all__"
   

forms_app/views.py
from django.shortcuts import render
from .forms import FormContatto
from .models import Contatto
from django.http import HttpResponse
from django.shortcuts import get_object_or_404,redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required

def contatti(request):

    if request.method=="POST":
        form=FormContatto(request.POST)

        if form.is_valid():
            print("il form è valido!")
            print("NOME: ", form.cleaned_data["nome"])
            print("COGNOME: ", form.cleaned_data["cognome"])
            print("EMAIL: ", form.cleaned_data["email"])
            print("CONTENUTO: ", form.cleaned_data["contenuto"])

            print("Salvo il contatto nel database")
            nuovo_contatto=form.save()
            print("new_post: ",nuovo_contatto)
            print(nuovo_contatto.nome)
            print(nuovo_contatto.cognome)
            print(nuovo_contatto.email)
            print(nuovo_contatto.contenuto)
            

            return HttpResponse("<h1>Grazie per averci contattato!</h1>")
    else:
        form=FormContatto()

    context={"form":form}
    return render(request, "contatto.html", context)

def lista_contatti(request):
    contatti=Contatto.objects.all()
    context={"contatti":contatti}
    return render(request,"lista_contatti.html",context)


@login_required(login_url="/accounts/login")
def modifica_contatto(request,pk):
    contatto=get_object_or_404(Contatto,id=pk)

    if request.method=="GET":
        form=FormContatto(instance=contatto)

    if request.method=="POST":
        form=FormContatto(request.POST, instance=contatto)
        if form.is_valid():
            form.save()
            return redirect('forms_app:lista_contatti')
        
    context={'form':form, 'contatto':contatto}
    return render(request, 'modifica_contatto.html',context)


@staff_member_required(login_url="/accounts/login")
def elimina_contatto(request,pk):
    contatto=get_object_or_404(Contatto,id=pk)
    if request.method=="POST":
        contatto.delete()
        return redirect('forms_app:lista_contatti')
    context={'contatto':contatto}
    return render(request, 'elimina_contatto.html',context)

forms_app/templates/contatto.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}{{block.super}} | Contatti{% endblock head_title %}


{% block content%}
<div class="container">
    <h1>Compila il form di contatto, ti risponderemo quanto prima!</h1>

    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-danger" value="INVIA">
    </form>
</div>

{% endblock content%}

forms_app/templates/elimina_contatto.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block head_title %}{{block.super}} | elimina_contatto{% endblock head_title %}

{%block content %}
<div class="container">
    <h1>Elimina contatto</h1>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-danger" value="CONFERMA ELIMINAZIONE">
    </form>
</div>
{% endblock content %}

forms_app/templates/lista_contatti.html
{% extends "base.html" %}

{%block title%}
    {{block.super}} | Lista contatti
{%endblock title%}

{%block content%}
    <h4>Lista contatti: </h4>

    <table border="1">
    <tr>
        {%if request.user.is_authenticated%}
            <td>Cancella</td>
            <td>Modifica</td>
        {%endif%}

        <td>Nome</td>
        <td>Cognome</td>
        <td>Email</td>
        <td>Contenuto</td>
    </tr>

    {% for contatto in contatti%}
    <tr>
    {%if request.user.is_authenticated%}
            <td><a href={%url 'forms_app:elimina_contatto' contatto.pk%}><i class="fas fa-eraser"></i></a></td>
            <td><a href={%url 'forms_app:modifica_contatto' contatto.pk%}><i class="far fa-edit"></i></a></td>
    {%endif%}

    <td>{{contatto.nome}}</td>
        <td>{{contatto.cognome}}</td>
        <td>{{contatto.email}}</td>
        <td>{{contatto.contenuto}}</td>
    </tr>

    {%endfor%}
    </table>

{% endblock content %}

forms_app/templates/modifica_contatto.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block head_title %}{{block.super}} | modifica_contatto{% endblock head_title %}

{%block content %}
<div class="container">
    <h1>Modifica contatto</h1>
    <form method="post">
        {% csrf_token %}

        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="SALVA MODIFICHE">
    </form>
</div>
{% endblock content%}