corsi_formazione/urls.py
from django.urls import path
from .views import index_corsi, view_a, view_b, view_c, view_d, view_e, view_f

app_name="corsi_formazione"
urlpatterns=[
    path('index_corsi',index_corsi, name="index_corsi"),
    path('view_a',view_a, name="view_a"),
    path('view_b/<int:pk>',view_b, name="view_b"),
    path('view_c',view_c, name="view_c"),
    path('view_d',view_d, name="view_d"),
    path('view_e',view_e, name="view_e"),
    path('view_f',view_f, name="view_f"),
   
]

news/urls.py
from django.urls import path
from news.views import index_root, home, articoloDetailView, listaArticoli, queryBase, giornalistaDetailView,index

app_name="news"
urlpatterns=[
    path('index_root',index_root, name="index_root"),
    path('homeview',home,name="homeview"),
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("lista_articoli", listaArticoli, name="lista_articoli"),
    path("lista_articoli/<int:pk>", listaArticoli, name="lista_articoli"),
    path("queryBase", queryBase, name="queryBase"),
    path("giornalisti/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
    path('index',index, name="index"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base,name='base'),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('news/',include("news.urls",namespace="news")),
    path('voti_app/',include("voti_app.urls",namespace="voti_app")),
    path('gestione_eventi_scolastici/',include("gestione_eventi_scolastici.urls",namespace="gestione_eventi_scolastici")),
    path('corsi_formazione/',include("corsi_formazione.urls",namespace="corsi_formazione")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),


]

corsi_formazione/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Corso(models.Model):
    """modello gerarchico di un giornalista"""
    titolo=models.CharField(max_length=20)
    descrizione=models.TextField()
    data_inizio=models.DateField(default=datetime.now(), blank=True)
    data_fine=models.DateField(default=datetime.now(), blank=True)
    posti_disponibili=models.IntegerField()

    def __str__ (self):
        return self.titolo
    
    class Meta:
        verbose_name="Corso"
        verbose_name_plural="Corsi"

corsi_formazione/views.py
from django.shortcuts import render, get_object_or_404
from .models import Corso
import datetime

#index contenente tutti i link delle pagine di quest'app
def index_corsi(request):
    return render(request,"index_corsi.html")

#Elenco dei corsi ordinati per data di inizio
def view_a(request):

    corsi_ordinati_inizio = Corso.objects.order_by('-data_inizio')
    
    context={"corsi_ordinati_inizio":corsi_ordinati_inizio,}
    return render(request, "view_a.html",context)

#Dettagli di un corso cliccato sulla view a.
def view_b(request, pk):
    corso=get_object_or_404(Corso, pk=pk)
    context={"corso":corso}
    return render(request, "view_b.html",context)

#Elenco dei corsi che iniziano dopo il 01/05/2025.
def view_c(request):
    corsi_dopo_data = Corso.objects.filter(data_inizio__gt=datetime.date(2025, 5, 1))
    context={"corsi_dopo_data":corsi_dopo_data,}
    return render(request, "view_c.html",context)

#Elenco dei corsi con meno di 20 posti disponibili.
def view_d(request):
    corsi_meno20 = Corso.objects.filter(posti_disponibili__lte=20)
    context={"corsi_meno20":corsi_meno20,}
    return render(request, "view_d.html",context)

#Elenco dei corsi che terminano entro il 30/04/2025.
def view_e(request):
    corsi_terminati_entro = Corso.objects.filter(data_fine__lt=datetime.date(2025, 4, 30))
    context={"corsi_terminati_entro":corsi_terminati_entro,}
    return render(request, "view_e.html",context)

#Visualizzare il corso con più posti disponibili, quello con meno posti e il totale dei posti disponibili:
def view_f(request):
    corso_piu_posti = Corso.objects.order_by('-posti_disponibili').first()
    corso_meno_posti = Corso.objects.order_by('posti_disponibili').first()

    elencoCorsi=Corso.objects.all()
    nTot=0
    for corso in elencoCorsi:
        nTot+=corso.posti_disponibili

    context={"corso_piu_posti":corso_piu_posti,"corso_meno_posti":corso_meno_posti,"nTot":nTot}
    return render(request, "view_f.html",context)








    

corsi_formazione/templates/index_corsi.html
{% extends "base.html" %}
{%block content%}
<h1>Benvenuto nel sistema di gestione dei Corsi di Formazione</h1>
<ul>
  <li><a href={% url 'corsi_formazione:view_a'%}>Lista_Corsi</a></li>
  <li><a href={% url 'corsi_formazione:view_b' 1%}>Dettagli dei Corsi</a></li>
  <li><a href={% url 'corsi_formazione:view_c'%}>Corsi che iniziano dopo il 01/05/2025</a></li>
  <li><a href={% url 'corsi_formazione:view_d'%}>Corsi con meno di 20 posti disponibili</a></li>
  <li><a href={% url 'corsi_formazione:view_e'%}>Corsi che terminano entro il 30/04/2025</a></li>
  <li><a href={% url 'corsi_formazione:view_f'%}>Statistiche Avanzate sui Corsi</a></li>
</ul>



{%endblock content%}

corsi_formazione/templates/view_a.html
{%extends "base.html"%}
{%block title%}Elenco corsi da data di inizio {%endblock title%}

{%block content%}
<h1>Elenco corsi da data di inizio:</h1>
<ul>
    {% for corso in corsi_ordinati_inizio %}
        <li><a href={% url 'corsi_formazione:view_b' corso.id %}>{{corso.titolo}}</a></li>
    {% endfor %}
</ul>

{%endblock content%}

corsi_formazione/templates/view_b.html
{% extends "base.html" %}

{%block title%}
    {{corso.titolo}}
{%endblock title%}

{%block content%}
    <h1>{{corso.titolo}}</h1>
    <h5>{{corso.descrizione}}</h5>
    <h5>{{corso.data_inizio}}</h5>
    <h5>{{corso.data_fine}}</h5>
    <h5>{{corso.posti}}</h5>
{% endblock content %}

corsi_formazione/templates/view_c.html
{%extends "base.html"%}
{%block title%}Elenco corsi con data inizio dopo al 01/05/2025 {%endblock title%}

{%block content%}
<h1>Elenco corsi con data inizio dopo al 01/05/2025:</h1>
<ul>
    {% for corso in corsi_dopo_data %}
        <li>{{corso.titolo}}</li>
    {% endfor %}
</ul>

{%endblock content%}

corsi_formazione/templates/view_d.html
{%extends "base.html"%}
{%block title%}Corsi con meno di 20 posti disponibili{%endblock title%}

{%block content%}
<h1>Corsi con meno di 20 posti disponibili:</h1>
<ul>
    {% for corso in corsi_meno20 %}
        <li>{{corso.titolo}}</li>
    {% endfor %}
</ul>

{%endblock content%}

corsi_formazione/templates/view_e.html
{%extends "base.html"%}
{%block title%}Corsi che terminano entro il 30/04/2025 {%endblock title%}

{%block content%}
<h1>Corsi che terminano entro il 30/04/2025:</h1>
<ul>
    {% for corso in corsi_terminati_entro %}
        <li>{{corso.titolo}}</li>
    {% endfor %}
</ul>

{%endblock content%}

corsi_formazione/templates/view_f.html
{%extends "base.html"%}
{%block title%}Statistiche Avanzate sui Corsi{%endblock title%}

{%block content%}
<h1>Statistiche Avanzate sui Corsi:</h1>
<h4>Corso con più posti disponibili: {{corso_piu_posti.titolo}} con posti: {{corso_piu_posti.posti_disponibili}}</h4>
<h4>Corso con meno posti disponibili: {{corso_meno_posti.titolo}} con posti: {{corso_meno_posti.posti_disponibili}}</h4>
<h4>Totale posti disponibili per tutti i corsi: {{nTot}}</h4>
        




{%endblock content%}