news/urls.py
from django.urls import path
from news.views import index_root, home, articoloDetailView, listaArticoli, queryBase, giornalistaDetailView,index

app_name="news"
urlpatterns=[
    path('index_root',index_root, name="index_root"),
    path('homeview',home,name="homeview"),
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("lista_articoli", listaArticoli, name="lista_articoli"),
    path("lista_articoli/<int:pk>", listaArticoli, name="lista_articoli"),
    path("queryBase", queryBase, name="queryBase"),
    path("giornalisti/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
    path('index',index, name="index"),
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage,welcome,lista, chi_siamo,variabili,index,index_root

app_name="prima_app"
urlpatterns=[
    path('index_root',index_root, name="index_root"),
    path('homepage',homepage, name="homepage"),
    path('welcome',welcome, name="welcome"),
    path('lista',lista, name="lista"),
    path('chi_siamo',chi_siamo, name="chi_siamo"),
    path('variabili',variabili, name="variabili"),
    path('',index, name="index"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base,name='base'),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('news/',include("news.urls",namespace="news")),
    path('voti_app/',include("voti_app.urls",namespace="voti_app")),
    path('gestione_eventi_scolastici/',include("gestione_eventi_scolastici.urls",namespace="gestione_eventi_scolastici")),
    path('corsi_formazione/',include("corsi_formazione.urls",namespace="corsi_formazione")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),


]

prima_app/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request,"homepage.html")

def welcome(request):
    return render(request,"welcome.html")

def lista(request):
    return render(request,"lista.html")

def chi_siamo(request):
    return render(request,"chi_siamo.html")

def variabili(request):
    context={
        'var1': 'Prima variabile',
        'var2': 'Seconda variabile',
        'var3': 'Terza variabile',
    }
    return render(request,"variabili.html",context)

def index(request):
    return render(request,"index.html")

def index_root(request):
    return render(request,"index_root.html")

prima_app/templates/chi_siamo.html
{%extends "base.html"%}
{%block title%}{{block.super}} chi siamo {%endblock title%}

{%block content%}
    
    <h1>Chi siamo</h1>

    <p>Lorem ipsummmmmm</p>

{%endblock content%}

prima_app/templates/homepage.html
{%extends "base.html"%}
{%block title%}{{block.super}} homepage {%endblock title%}

{%block content%}
    <h1>Benvenuto</h1>
{%endblock content%}

prima_app/templates/index.html
<!DOCTYPE html>
<html lang="it">
    <head>
        <meta charset="UTF-8">
        <title>Index</title>
    </head>
    <body>
        <ol>
            <li><a href="{% url 'prima_app:index_root'%}">Index_root</a></li>
            <li><a href="{% url 'prima_app:homepage'%}">Home page benvenuto</a></li>
            <li><a href="{% url 'prima_app:welcome'%}">Welcome</a></li>
            <li><a href="{% url 'prima_app:lista'%}">Lista</a></li>
            <li><a href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a></li>
            <li><a href="{% url 'prima_app:variabili'%}">Variabili</a></li>
        </ol>
    </body>
</html>

prima_app/templates/lista.html
{%extends "base.html"%}
{%block title%}{{block.super}} lista {%endblock title%}

{%block content%}

    <ol>
        <li>Primo</li>
        <li>Secondo</li>
        <li>Terzo</li>
    </ol>
{%endblock content%}

prima_app/templates/variabili.html
{%extends "base.html"%}
{%block title%}{{block.super}} variabili {%endblock title%}

{%block content%}
        <ol>
            <li>{{var1}}</li>
            <li>{{var2}}</li>
            <li>{{var3}}</li>
        </ol>
{%endblock content%}

prima_app/templates/welcome.html
{%extends "base.html"%}
{%block title%}{{block.super}} welcome {%endblock title%}

{%block content%}
    <h1>Welcome</h1>
{%endblock content%}